apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: payroll-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    vault:
      server: http://openbao-external.payroll-dev.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: payroll-dev
          serviceAccountRef:
            name: payroll-secrets
            audiences:
              - vault
