apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-java-app-database
  namespace: demo-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: demo-java-app-database
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: demo-java-app/dev/database
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: demo-java-app/dev/database
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: demo-java-app/dev/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: demo-java-app/dev/database
        property: password
