apiVersion: v1
kind: Service
metadata:
  name: openbao-external
  namespace: demo-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
