replicaCount: 1

image:
  repository: demo-java-app
  tag: "1.0.0-local"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: demo-java-app.localhost
      paths:
        - path: /
          pathType: Prefix
