apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payroll.fullname" . }}
  labels:
    {{- include "payroll.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "payroll.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "payroll.labels" . | nindent 8 }}
    spec:
      containers:
        - name: payroll
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom: {secretKeyRef: {name: {{ .Values.secret.name }}, key: DB_HOST}}
            - name: DB_PORT
              valueFrom: {secretKeyRef: {name: {{ .Values.secret.name }}, key: DB_PORT}}
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: {{ .Values.secret.name }}, key: DB_USER}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: {{ .Values.secret.name }}, key: DB_PASSWORD}}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet: {path: /, port: http}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /, port: http}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: content
          configMap:
            name: {{ include "payroll.fullname" . }}-content
