apiVersion: v1
kind: Service
metadata:
  name: {{ include "payroll.fullname" . }}
  labels:
    {{- include "payroll.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "payroll.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
